name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      doRelease:
        description: "Publish new release"
        type: boolean
        default: false
        required: false

env:
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write

jobs:
  build_arm64:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        run: |
          echo "image_name=${{ env.REGISTRY }}/${{ github.repository_owner }}/mysql" >> $GITHUB_OUTPUT
          echo "version=5.7.44" >> $GITHUB_OUTPUT
          echo "tag=${{ env.REGISTRY }}/${{ github.repository_owner }}/mysql:5.7.44-linux-arm64v8" >> $GITHUB_OUTPUT
      - name: prepare
        run: |
          sudo apt-get update && sudo apt-get install -y wget
      - name: build arm64 package
        run: |
          make build-all-one-image-arm64v8
        env:
          DOCKER_REGISTRY: ${{ env.REGISTRY }}/
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to registry
        run: |
          docker push ${{ steps.meta.outputs.tag }}